// src/components/pages/WildBirdGuide.vue
<template>
  <div class="guide-page-bg">
    <div class="guide-card">

      <!-- ══ HEADER ══════════════════════════════════════════════════════ -->
      <div class="guide-header">
        <div class="guide-header__deco">🦜</div>
        <h2 class="guide-header__title">發現受傷野鳥，怎麼辦？</h2>
        <p class="guide-header__desc">依照以下步驟判斷狀況、緊急處置，再聯繫專業救傷單位。</p>
        <div class="guide-header__bars">
          <div class="bar bar--orange-lg" />
          <div class="bar bar--green" />
          <div class="bar bar--orange-sm" />
        </div>
      </div>

      <!-- ══ SECTION 1 — 如何判斷野鳥受傷？(5 signs) ═══════════════════ -->
      <div class="guide-section">
        <SectionTitle title="如何判斷野鳥受傷？" />
        <div class="signs-grid">
          <div v-for="s in signs" :key="s.label" class="sign-card">
            <div class="sign-card__emoji">{{ s.emoji }}</div>
            <div class="sign-card__label">{{ s.label }}</div>
            <div class="sign-card__desc">{{ s.desc }}</div>
          </div>
        </div>
      </div>

      <!-- ══ SECTION 2 — 野鳥年齡怎麼分？(3 age types) ════════════════ -->
      <div class="guide-section guide-section--tinted">
        <SectionTitle title="野鳥年齡怎麼分？" />
        <div class="age-grid">
          <div
            v-for="card in ageCards"
            :key="card.name"
            class="age-card"
            :style="{ borderTopColor: card.borderColor }"
          >
            <div class="age-card__badge-row">
              <span
                class="age-card__badge"
                :style="{ backgroundColor: card.badgeColor }"
              >{{ card.badge }}</span>
            </div>
            <div class="age-card__emoji">{{ card.emoji }}</div>
            <div class="age-card__name">{{ card.name }}</div>
            <ul class="age-card__list">
              <li
                v-for="(pt, i) in card.points"
                :key="i"
                class="age-card__list-item"
                :class="{ 'age-card__list-item--action': pt.startsWith('➜') }"
                :style="{
                  color: pt.startsWith('➜') ? card.badgeColor : '#555',
                  fontWeight: pt.startsWith('➜') ? 600 : 400,
                  borderTop: i === card.points.length - 1 ? '1px dashed rgba(0,0,0,0.08)' : 'none',
                  paddingTop: i === card.points.length - 1 ? '8px' : '0',
                  marginTop: i === card.points.length - 1 ? '4px' : '0',
                }"
              >
                {{ pt.startsWith('➜') ? pt : `• ${pt}` }}
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- ══ SECTION 3 — 緊急處置步驟 ════════════════════════════════ -->
      <div class="guide-section">
        <SectionTitle title="緊急處置步驟" />

        <div class="steps-timeline">
          <template v-for="(step, idx) in steps" :key="step.n">
            <!-- Step row -->
            <div class="step-row">
              <div class="step-row__badge">{{ step.n }}</div>
              <div class="step-row__body">
                <div class="step-row__title">{{ step.title }}</div>
                <div class="step-row__desc">{{ step.desc }}</div>
              </div>
            </div>
            <!-- Connector between steps -->
            <div v-if="idx < steps.length - 1" class="step-connector" />
          </template>
        </div>

        <!-- Warning banner -->
        <div class="warn-banner">
          <span class="warn-banner__icon">⚠️</span>
          <span class="warn-banner__text">
            請勿自行放生！放生不等於救援，外來種或受傷個體放生反而造成二次傷害。
          </span>
        </div>
      </div>

      <!-- ══ SECTION 4 — 救傷聯絡電話 ════════════════════════════════ -->
      <div class="guide-section guide-section--tinted">
        <SectionTitle title="救傷聯絡電話" />

        <div class="contact-grid">
          <div v-for="c in contacts" :key="c.org" class="contact-row">
            <span class="contact-row__org">{{ c.org }}</span>
            <span class="contact-row__phone">{{ c.phone }}</span>
          </div>
        </div>

        <!-- PDF download button -->
        <div class="download-wrap">
          <a
            href="/downloads/wild-bird/wild-bird-rescue-guide.pdf"
            download
            class="download-btn"
          >
            📄 下載完整救傷傳單 PDF
          </a>
        </div>
      </div>

      <!-- ══ FOOTER ════════════════════════════════════════════════════ -->
      <div class="guide-footer">
        <span class="guide-footer__left">資料來源：台北鳥會野鳥救傷中心 · 中科大野鳥救傷社群</span>
        <span class="guide-footer__right">野鳥救傷指引</span>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
import { defineComponent, h } from 'vue'

// ── Inline SectionTitle component ─────────────────────────────────────────
const SectionTitle = defineComponent({
  props: { title: { type: String, required: true } },
  setup(props) {
    return () =>
      h('div', { class: 'section-title' }, [
        h('div', { class: 'section-title__text' }, props.title),
        h('div', { class: 'section-title__bar' }),
      ])
  },
})

// ── Data ──────────────────────────────────────────────────────────────────
const signs = [
  { emoji: '🩹', label: '身上有傷口',   desc: '出血、骨折、脫臼等明顯外傷' },
  { emoji: '😵', label: '精神萎靡',     desc: '對周圍環境無反應、眼神渙散' },
  { emoji: '🌡️', label: '體溫偏低',     desc: '身體冰涼、無法維持正常體溫' },
  { emoji: '🪶', label: '翅膀不對稱',   desc: '單側下垂或無法正常收攏' },
  { emoji: '💧', label: '羽毛凌亂濕透', desc: '羽毛糾結、無法正常防水保溫' },
]

const ageCards = [
  {
    emoji: '🐣',
    name: '雛鳥',
    badge: '需要幫助',
    badgeColor: '#F57600',
    borderColor: '#F57600',
    points: [
      '全身絨毛或幾乎裸露',
      '眼睛尚未睜開或剛睜開',
      '無法站立，依賴親鳥餵食',
      '➜ 請立即聯繫救傷單位',
    ],
  },
  {
    emoji: '🐦',
    name: '幼鳥',
    badge: '視情況判斷',
    badgeColor: '#2c5f2d',
    borderColor: '#2c5f2d',
    points: [
      '羽毛已漸長齊，但仍蓬鬆',
      '能短距離跳躍，翅膀尚弱',
      '可能是正常的離巢學飛',
      '➜ 觀察親鳥是否仍在附近',
    ],
  },
  {
    emoji: '🦅',
    name: '成鳥',
    badge: '通常需要救援',
    badgeColor: '#888',
    borderColor: '#888',
    points: [
      '羽毛完整、對人類戒心強',
      '若能被人輕易捉住通常表示受傷',
      '行動遲緩或無法飛翔',
      '➜ 確認異常後聯繫救傷單位',
    ],
  },
]

const steps = [
  {
    n: 1,
    title: '確認羽毛是否濕透',
    desc: '若羽毛沾水潮濕，請先用乾紙巾輕輕吸乾，不可用吹風機。',
  },
  {
    n: 2,
    title: '補充電解質水分',
    desc: '以運動飲料與水按 1：5～6 比例稀釋，用棉棒或吸管從嘴尖緩慢滴入，切勿滴入鼻孔。',
  },
  {
    n: 3,
    title: '禁止自行餵食',
    desc: '不可餵食麵包、米飯、牛奶等食物，不當餵食會造成嗆吸或消化道損傷。',
  },
  {
    n: 4,
    title: '製作野鳥運送箱',
    desc: '選用有蓋紙箱，底部鋪報紙（勿用毛巾、布料），側邊挖氣孔，不要塞太滿。',
  },
  {
    n: 5,
    title: '立即聯絡救傷單位',
    desc: '準備好發現地點、鳥的狀況描述，依下方電話聯繫最近的救傷單位。',
  },
]

const contacts = [
  { org: '台北鳥會野鳥救傷中心',   phone: '02-8732-8891' },
  { org: '台北市動物保護處',       phone: '02-8789-7158' },
  { org: '24小時動物救援專線',     phone: '02-8791-3064' },
  { org: '新北市動物保護防疫處',   phone: '02-2959-6353' },
  { org: '特生中心野生動物急救站', phone: '049-2761313'  },
  { org: '民眾服務專線',           phone: '1999'         },
]
</script>

<style scoped lang="scss">
/* ── Page background ──────────────────────────────────────────────────── */
.guide-page-bg {
  min-height: 100vh;
  background-color: #d3e3bb;
  background-image:
    radial-gradient(ellipse at 20% 30%, rgba(100,140,60,0.18) 0%, transparent 60%),
    radial-gradient(ellipse at 80% 70%, rgba(60,100,40,0.14) 0%, transparent 55%);
  padding: 32px 16px 48px;
  display: flex;
  justify-content: center;
  align-items: flex-start;
}

/* ── White card ───────────────────────────────────────────────────────── */
.guide-card {
  width: 100%;
  max-width: 1200px;
  background-color: #fff;
  border-radius: 16px;
  box-shadow: 0 8px 40px rgba(0,0,0,0.18), 0 2px 8px rgba(0,0,0,0.1);
  overflow: hidden;
}

/* ── Header ───────────────────────────────────────────────────────────── */
.guide-header {
  padding: 36px 40px 28px;
  border-bottom: 1px solid rgba(44,95,45,0.12);
  background: linear-gradient(135deg, rgba(211,227,187,0.5) 0%, rgba(255,255,255,0) 60%);
  position: relative;

  &__deco {
    position: absolute;
    top: 18px;
    right: 40px;
    font-size: 68px;
    opacity: 0.07;
    user-select: none;
    line-height: 1;
    transform: rotate(15deg);
  }

  &__title {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 28px;
    font-weight: 700;
    color: #2c5f2d;
    margin: 0 0 10px;
    letter-spacing: 0.04em;
    line-height: 1.3;
  }

  &__desc {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 15px;
    color: #555;
    margin: 0;
    line-height: 1.7;
  }

  &__bars {
    margin-top: 16px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
}

.bar {
  height: 3px;
  border-radius: 2px;
  &--orange-lg { width: 32px; background-color: #F57600; }
  &--green     { width: 16px; background-color: #2c5f2d; }
  &--orange-sm { width: 8px;  background-color: #F78B26; }
}

/* ── Section wrapper ──────────────────────────────────────────────────── */
.guide-section {
  padding: 28px 40px 32px;

  &--tinted {
    background-color: rgba(211,227,187,0.25);
  }
}

/* ── SectionTitle (component styles) ─────────────────────────────────── */
:deep(.section-title) {
  margin-bottom: 20px;
}
:deep(.section-title__text) {
  font-family: 'Noto Sans TC', sans-serif;
  font-size: 20px;
  font-weight: 700;
  color: #2c5f2d;
  margin-bottom: 8px;
}
:deep(.section-title__bar) {
  width: 36px;
  height: 3px;
  background-color: #F57600;
  border-radius: 2px;
}

/* ── Signs grid ───────────────────────────────────────────────────────── */
.signs-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 16px;
}

.sign-card {
  background-color: #fff8f0;
  border: 1px solid rgba(245,118,0,0.15);
  border-radius: 10px;
  padding: 18px 12px;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;

  &__emoji {
    font-size: 36px;
    line-height: 1.2;
  }

  &__label {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 14px;
    font-weight: 700;
    color: #2c5f2d;
  }

  &__desc {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 12px;
    color: #777;
    line-height: 1.5;
  }
}

/* ── Age cards grid ───────────────────────────────────────────────────── */
.age-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
}

.age-card {
  background-color: #fff;
  border-radius: 12px;
  padding: 22px 20px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
  border-top: 3px solid transparent; // overridden by :style

  &__badge-row {
    display: flex;
    justify-content: flex-end;
    margin-bottom: 10px;
  }

  &__badge {
    color: #fff;
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 11px;
    font-weight: 600;
    border-radius: 20px;
    padding: 3px 10px;
    letter-spacing: 0.02em;
  }

  &__emoji {
    font-size: 40px;
    text-align: center;
    line-height: 1.2;
    margin-bottom: 10px;
  }

  &__name {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 18px;
    font-weight: 700;
    color: #2c5f2d;
    text-align: center;
    margin-bottom: 14px;
  }

  &__list {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  &__list-item {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 13px;
    line-height: 1.8;
  }
}

/* ── Steps timeline ───────────────────────────────────────────────────── */
.steps-timeline {
  display: flex;
  flex-direction: column;
  gap: 0;
}

.step-row {
  display: flex;
  align-items: flex-start;
  gap: 16px;

  &__badge {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background-color: #F57600;
    color: #fff;
    font-family: 'Inter', sans-serif;
    font-size: 16px;
    font-weight: 700;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 2px 8px rgba(245,118,0,0.3);
  }

  &__body {
    padding-top: 6px;
    flex: 1;
  }

  &__title {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 15px;
    font-weight: 700;
    color: #2c5f2d;
    margin-bottom: 4px;
  }

  &__desc {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 13px;
    color: #555;
    line-height: 1.6;
  }
}

.step-connector {
  width: 2px;
  height: 20px;
  background-color: rgba(245,118,0,0.3);
  margin-left: 19px;
  margin-top: 4px;
  margin-bottom: 4px;
  border-radius: 1px;
}

/* ── Warning banner ───────────────────────────────────────────────────── */
.warn-banner {
  margin-top: 24px;
  background-color: rgba(220,38,38,0.06);
  border: 1px solid rgba(220,38,38,0.2);
  border-radius: 8px;
  padding: 12px 20px;
  display: flex;
  align-items: center;
  gap: 10px;

  &__icon { font-size: 18px; flex-shrink: 0; }

  &__text {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 13px;
    color: #b91c1c;
    line-height: 1.6;
  }
}

/* ── Contact grid ─────────────────────────────────────────────────────── */
.contact-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 0 24px;
}

.contact-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px dashed rgba(44,95,45,0.15);
  padding: 10px 0;
  gap: 12px;

  &__org {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 14px;
    font-weight: 600;
    color: #2c5f2d;
  }

  &__phone {
    background-color: #fff;
    border: 1px solid rgba(44,95,45,0.2);
    border-radius: 6px;
    padding: 4px 12px;
    font-family: 'Inter', sans-serif;
    font-size: 14px;
    font-weight: 600;
    color: #2c5f2d;
    letter-spacing: 0.03em;
    white-space: nowrap;
    flex-shrink: 0;
  }
}

/* ── Download button ──────────────────────────────────────────────────── */
.download-wrap {
  margin-top: 24px;
  display: flex;
  justify-content: center;
}

.download-btn {
  background-color: #F57600;
  color: #fff;
  font-family: 'Noto Sans TC', sans-serif;
  font-size: 15px;
  font-weight: 700;
  padding: 12px 32px;
  border-radius: 8px;
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  box-shadow: 0 4px 16px rgba(245,118,0,0.35);
  transition: background-color 0.2s ease, transform 0.15s ease;

  &:hover {
    background-color: #d4620a;
    transform: translateY(-1px);
  }
}

/* ── Footer ───────────────────────────────────────────────────────────── */
.guide-footer {
  padding: 16px 32px;
  border-top: 1px solid rgba(44,95,45,0.1);
  background-color: rgba(211,227,187,0.25);
  display: flex;
  align-items: center;
  justify-content: space-between;

  &__left {
    font-family: 'Noto Sans TC', sans-serif;
    font-size: 12px;
    color: #888;
  }

  &__right {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    color: #aaa;
  }
}

/* ── Responsive ───────────────────────────────────────────────────────── */
@media (max-width: 768px) {
  .signs-grid   { grid-template-columns: repeat(3, 1fr); }
  .age-grid     { grid-template-columns: repeat(2, 1fr); }
  .contact-grid { grid-template-columns: 1fr; }

  .guide-header,
  .guide-section { padding-left: 24px; padding-right: 24px; }
}

@media (max-width: 480px) {
  .signs-grid { grid-template-columns: repeat(2, 1fr); }
  .age-grid   { grid-template-columns: 1fr; }

  .guide-header,
  .guide-section { padding-left: 16px; padding-right: 16px; }
}
</style>

// _design/WildBird/app/components/WildBirdGuide.tsx
const signs = [
  { emoji: "🩹", label: "身上有傷口",   desc: "出血、骨折、脫臼等明顯外傷" },
  { emoji: "😵", label: "精神萎靡",     desc: "對周圍環境無反應、眼神渙散" },
  { emoji: "🌡️", label: "體溫偏低",     desc: "身體冰涼、無法維持正常體溫" },
  { emoji: "🪶", label: "翅膀不對稱",   desc: "單側下垂或無法正常收攏" },
  { emoji: "💧", label: "羽毛凌亂濕透", desc: "羽毛糾結、無法正常防水保溫" },
];

const ageCards = [
  {
    emoji: "🐣",
    name: "雛鳥",
    badge: "需要幫助",
    badgeColor: "#F57600",
    borderColor: "#F57600",
    points: [
      "全身絨毛或幾乎裸露",
      "眼睛尚未睜開或剛睜開",
      "無法站立，依賴親鳥餵食",
      "➜ 請立即聯繫救傷單位",
    ],
  },
  {
    emoji: "🐦",
    name: "幼鳥",
    badge: "視情況判斷",
    badgeColor: "#2c5f2d",
    borderColor: "#2c5f2d",
    points: [
      "羽毛已漸長齊，但仍蓬鬆",
      "能短距離跳躍，翅膀尚弱",
      "可能是正常的離巢學飛",
      "➜ 觀察親鳥是否仍在附近",
    ],
  },
  {
    emoji: "🦅",
    name: "成鳥",
    badge: "通常需要救援",
    badgeColor: "#888",
    borderColor: "#888",
    points: [
      "羽毛完整、對人類戒心強",
      "若能被人輕易捉住通常表示受傷",
      "行動遲緩或無法飛翔",
      "➜ 確認異常後聯繫救傷單位",
    ],
  },
];

const steps = [
  {
    n: 1,
    title: "確認羽毛是否濕透",
    desc: "若羽毛沾水潮濕，請先用乾紙巾輕輕吸乾，不可用吹風機。",
  },
  {
    n: 2,
    title: "補充電解質水分",
    desc: "以運動飲料與水按 1：5～6 比例稀釋，用棉棒或吸管從嘴尖緩慢滴入，切勿滴入鼻孔。",
  },
  {
    n: 3,
    title: "禁止自行餵食",
    desc: "不可餵食麵包、米飯、牛奶等食物，不當餵食會造成嗆吸或消化道損傷。",
  },
  {
    n: 4,
    title: "製作野鳥運送箱",
    desc: "選用有蓋紙箱，底部鋪報紙（勿用毛巾、布料），側邊挖氣孔，不要塞太滿。",
  },
  {
    n: 5,
    title: "立即聯絡救傷單位",
    desc: "準備好發現地點、鳥的狀況描述，依下方電話聯繫最近的救傷單位。",
  },
];

const contacts = [
  { org: "台北鳥會野鳥救傷中心",  phone: "02-8732-8891" },
  { org: "台北市動物保護處",      phone: "02-8789-7158" },
  { org: "24小時動物救援專線",    phone: "02-8791-3064" },
  { org: "新北市動物保護防疫處",  phone: "02-2959-6353" },
  { org: "特生中心野生動物急救站", phone: "049-2761313"  },
  { org: "民眾服務專線",          phone: "1999"          },
];

// ── Reusable section heading ──────────────────────────────────────────────
function SectionTitle({ title }: { title: string }) {
  return (
    <div style={{ marginBottom: "20px" }}>
      <div
        style={{
          fontFamily: "'Noto Sans TC', sans-serif",
          fontSize: "20px",
          fontWeight: 700,
          color: "#2c5f2d",
          marginBottom: "8px",
        }}
      >
        {title}
      </div>
      <div
        style={{
          width: "36px",
          height: "3px",
          backgroundColor: "#F57600",
          borderRadius: "2px",
        }}
      />
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────
export function WildBirdGuide() {
  return (
    <div
      style={{
        minHeight: "100vh",
        backgroundColor: "#d3e3bb",
        backgroundImage:
          "radial-gradient(ellipse at 20% 30%, rgba(100,140,60,0.18) 0%, transparent 60%), radial-gradient(ellipse at 80% 70%, rgba(60,100,40,0.14) 0%, transparent 55%)",
        padding: "32px 16px 48px",
        display: "flex",
        justifyContent: "center",
        alignItems: "flex-start",
      }}
    >
      {/* White card container */}
      <div
        style={{
          width: "100%",
          maxWidth: "1200px",
          backgroundColor: "#FFFFFF",
          borderRadius: "16px",
          boxShadow: "0 8px 40px rgba(0,0,0,0.18), 0 2px 8px rgba(0,0,0,0.1)",
          overflow: "hidden",
        }}
      >

        {/* ══ SECTION 1 — HEADER ══════════════════════════════════════════ */}
        <div
          style={{
            padding: "36px 40px 28px",
            borderBottom: "1px solid rgba(44,95,45,0.12)",
            background: "linear-gradient(135deg, rgba(211,227,187,0.5) 0%, rgba(255,255,255,0) 60%)",
            position: "relative",
          }}
        >
          {/* Decorative emoji */}
          <div
            style={{
              position: "absolute",
              top: "18px",
              right: "40px",
              fontSize: "68px",
              opacity: 0.07,
              userSelect: "none",
              lineHeight: 1,
              transform: "rotate(15deg)",
            }}
          >
            🦜
          </div>

          <h2
            style={{
              fontFamily: "'Noto Sans TC', sans-serif",
              fontSize: "28px",
              fontWeight: 700,
              color: "#2c5f2d",
              margin: "0 0 10px",
              letterSpacing: "0.04em",
              lineHeight: 1.3,
            }}
          >
            發現受傷野鳥，怎麼辦？
          </h2>
          <p
            style={{
              fontFamily: "'Noto Sans TC', sans-serif",
              fontSize: "15px",
              color: "#555555",
              margin: 0,
              lineHeight: 1.7,
            }}
          >
            依照以下步驟判斷狀況、緊急處置，再聯繫專業救傷單位。
          </p>

          {/* Decorative bars */}
          <div style={{ marginTop: "16px", display: "flex", alignItems: "center", gap: "8px" }}>
            <div style={{ width: "32px", height: "3px", backgroundColor: "#F57600", borderRadius: "2px" }} />
            <div style={{ width: "16px", height: "3px", backgroundColor: "#2c5f2d", borderRadius: "2px" }} />
            <div style={{ width: "8px",  height: "3px", backgroundColor: "#F78B26", borderRadius: "2px" }} />
          </div>
        </div>

        {/* ══ SECTION 2 — 5 SIGNS ═════════════════════════════════════════ */}
        <div style={{ padding: "28px 40px 32px" }}>
          <SectionTitle title="如何判斷野鳥受傷？" />
          <div
            className="signs-grid"
            style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "16px" }}
          >
            {signs.map((s) => (
              <div
                key={s.label}
                style={{
                  backgroundColor: "#fff8f0",
                  border: "1px solid rgba(245,118,0,0.15)",
                  borderRadius: "10px",
                  padding: "18px 12px",
                  textAlign: "center",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: "8px",
                }}
              >
                <div style={{ fontSize: "36px", lineHeight: 1.2 }}>{s.emoji}</div>
                <div
                  style={{
                    fontFamily: "'Noto Sans TC', sans-serif",
                    fontSize: "14px",
                    fontWeight: 700,
                    color: "#2c5f2d",
                  }}
                >
                  {s.label}
                </div>
                <div
                  style={{
                    fontFamily: "'Noto Sans TC', sans-serif",
                    fontSize: "12px",
                    color: "#777",
                    lineHeight: 1.5,
                  }}
                >
                  {s.desc}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ══ SECTION 3 — AGE TYPES ═══════════════════════════════════════ */}
        <div
          style={{
            backgroundColor: "rgba(211,227,187,0.25)",
            padding: "28px 40px 32px",
          }}
        >
          <SectionTitle title="野鳥年齡怎麼分？" />
          <div
            className="age-grid"
            style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px" }}
          >
            {ageCards.map((card) => (
              <div
                key={card.name}
                style={{
                  backgroundColor: "#FFFFFF",
                  borderRadius: "12px",
                  padding: "22px 20px",
                  boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
                  borderTop: `3px solid ${card.borderColor}`,
                }}
              >
                {/* Badge */}
                <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: "10px" }}>
                  <span
                    style={{
                      backgroundColor: card.badgeColor,
                      color: "#fff",
                      fontFamily: "'Noto Sans TC', sans-serif",
                      fontSize: "11px",
                      fontWeight: 600,
                      borderRadius: "20px",
                      padding: "3px 10px",
                      letterSpacing: "0.02em",
                    }}
                  >
                    {card.badge}
                  </span>
                </div>

                {/* Emoji */}
                <div style={{ fontSize: "40px", textAlign: "center", lineHeight: 1.2, marginBottom: "10px" }}>
                  {card.emoji}
                </div>

                {/* Name */}
                <div
                  style={{
                    fontFamily: "'Noto Sans TC', sans-serif",
                    fontSize: "18px",
                    fontWeight: 700,
                    color: "#2c5f2d",
                    textAlign: "center",
                    marginBottom: "14px",
                  }}
                >
                  {card.name}
                </div>

                {/* Points */}
                <ul style={{ margin: 0, padding: 0, listStyle: "none" }}>
                  {card.points.map((pt, i) => (
                    <li
                      key={i}
                      style={{
                        fontFamily: "'Noto Sans TC', sans-serif",
                        fontSize: "13px",
                        color: pt.startsWith("➜") ? card.badgeColor : "#555",
                        lineHeight: 1.8,
                        fontWeight: pt.startsWith("➜") ? 600 : 400,
                        paddingLeft: pt.startsWith("➜") ? 0 : "0",
                        borderTop: i === card.points.length - 1 ? "1px dashed rgba(0,0,0,0.08)" : "none",
                        paddingTop: i === card.points.length - 1 ? "8px" : 0,
                        marginTop: i === card.points.length - 1 ? "4px" : 0,
                      }}
                    >
                      {pt.startsWith("➜") ? pt : `• ${pt}`}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* ══ SECTION 4 — 緊急處置步驟 ════════════════════════════════════ */}
        <div style={{ padding: "28px 40px 32px" }}>
          <SectionTitle title="緊急處置步驟" />

          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {steps.map((step, idx) => (
              <div key={step.n}>
                {/* Step row */}
                <div style={{ display: "flex", alignItems: "flex-start", gap: "16px" }}>
                  {/* Circle badge */}
                  <div
                    style={{
                      width: "40px",
                      height: "40px",
                      borderRadius: "50%",
                      backgroundColor: "#F57600",
                      color: "#fff",
                      fontFamily: "'Inter', sans-serif",
                      fontSize: "16px",
                      fontWeight: 700,
                      flexShrink: 0,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      boxShadow: "0 2px 8px rgba(245,118,0,0.3)",
                    }}
                  >
                    {step.n}
                  </div>

                  {/* Text */}
                  <div style={{ paddingTop: "6px", flex: 1 }}>
                    <div
                      style={{
                        fontFamily: "'Noto Sans TC', sans-serif",
                        fontSize: "15px",
                        fontWeight: 700,
                        color: "#2c5f2d",
                        marginBottom: "4px",
                      }}
                    >
                      {step.title}
                    </div>
                    <div
                      style={{
                        fontFamily: "'Noto Sans TC', sans-serif",
                        fontSize: "13px",
                        color: "#555",
                        lineHeight: 1.6,
                      }}
                    >
                      {step.desc}
                    </div>
                  </div>
                </div>

                {/* Connector line between steps */}
                {idx < steps.length - 1 && (
                  <div
                    style={{
                      width: "2px",
                      height: "20px",
                      backgroundColor: "rgba(245,118,0,0.3)",
                      marginLeft: "19px",
                      marginTop: "4px",
                      marginBottom: "4px",
                      borderRadius: "1px",
                    }}
                  />
                )}
              </div>
            ))}
          </div>

          {/* Warning banner */}
          <div
            style={{
              marginTop: "24px",
              backgroundColor: "rgba(220,38,38,0.06)",
              border: "1px solid rgba(220,38,38,0.2)",
              borderRadius: "8px",
              padding: "12px 20px",
              display: "flex",
              alignItems: "center",
              gap: "10px",
            }}
          >
            <span style={{ fontSize: "18px", flexShrink: 0 }}>⚠️</span>
            <span
              style={{
                fontFamily: "'Noto Sans TC', sans-serif",
                fontSize: "13px",
                color: "#b91c1c",
                lineHeight: 1.6,
              }}
            >
              請勿自行放生！放生不等於救援，外來種或受傷個體放生反而造成二次傷害。
            </span>
          </div>
        </div>

        {/* ══ SECTION 5 — 救傷聯絡電話 ════════════════════════════════════ */}
        <div
          style={{
            backgroundColor: "rgba(211,227,187,0.25)",
            padding: "28px 40px 32px",
          }}
        >
          <SectionTitle title="救傷聯絡電話" />

          <div
            className="contact-grid"
            style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "0 24px" }}
          >
            {contacts.map((c) => (
              <div
                key={c.org}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  borderBottom: "1px dashed rgba(44,95,45,0.15)",
                  paddingBottom: "10px",
                  paddingTop: "10px",
                  gap: "12px",
                }}
              >
                {/* Org name */}
                <span
                  style={{
                    fontFamily: "'Noto Sans TC', sans-serif",
                    fontSize: "14px",
                    fontWeight: 600,
                    color: "#2c5f2d",
                  }}
                >
                  {c.org}
                </span>

                {/* Phone chip */}
                <span
                  style={{
                    backgroundColor: "#fff",
                    border: "1px solid rgba(44,95,45,0.2)",
                    borderRadius: "6px",
                    padding: "4px 12px",
                    fontFamily: "'Inter', sans-serif",
                    fontSize: "14px",
                    fontWeight: 600,
                    color: "#2c5f2d",
                    letterSpacing: "0.03em",
                    whiteSpace: "nowrap",
                    flexShrink: 0,
                  }}
                >
                  {c.phone}
                </span>
              </div>
            ))}
          </div>

          {/* Download button */}
          <div style={{ marginTop: "24px", display: "flex", justifyContent: "center" }}>
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              style={{
                backgroundColor: "#F57600",
                color: "#fff",
                fontFamily: "'Noto Sans TC', sans-serif",
                fontSize: "15px",
                fontWeight: 700,
                padding: "12px 32px",
                borderRadius: "8px",
                textDecoration: "none",
                display: "inline-flex",
                alignItems: "center",
                gap: "8px",
                boxShadow: "0 4px 16px rgba(245,118,0,0.35)",
                transition: "background 0.2s ease, transform 0.15s ease",
              }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLAnchorElement).style.backgroundColor = "#d4620a";
                (e.currentTarget as HTMLAnchorElement).style.transform = "translateY(-1px)";
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLAnchorElement).style.backgroundColor = "#F57600";
                (e.currentTarget as HTMLAnchorElement).style.transform = "translateY(0)";
              }}
            >
              📄 下載完整救傷傳單 PDF
            </a>
          </div>
        </div>

        {/* ══ FOOTER ══════════════════════════════════════════════════════ */}
        <div
          style={{
            padding: "16px 32px",
            borderTop: "1px solid rgba(44,95,45,0.1)",
            backgroundColor: "rgba(211,227,187,0.25)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <span
            style={{
              fontFamily: "'Noto Sans TC', sans-serif",
              fontSize: "12px",
              color: "#888",
            }}
          >
            資料來源：台北鳥會野鳥救傷中心 · 中科大野鳥救傷社群
          </span>
          <span
            style={{
              fontFamily: "'Inter', sans-serif",
              fontSize: "12px",
              color: "#aaa",
            }}
          >
            野鳥救傷指引
          </span>
        </div>
      </div>

      {/* Responsive styles */}
      <style>{`
        @media (max-width: 768px) {
          .signs-grid   { grid-template-columns: repeat(3, 1fr) !important; }
          .age-grid     { grid-template-columns: repeat(2, 1fr) !important; }
          .contact-grid { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 480px) {
          .signs-grid { grid-template-columns: repeat(2, 1fr) !important; }
          .age-grid   { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
